/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package pcd.practica10;

import java.util.concurrent.locks.ReentrantReadWriteLock;

/**
 *
 * @author Pepe
 */
public class Main extends java.awt.Frame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Main m = new Main();
        m.setSize(600, 400);
        m.setTitle("Practica 10");
        m.setVisible(true);
        
        mCanvas cv = new mCanvas(600, 400);
        m.add(cv);
        ReentrantReadWriteLock L = new ReentrantReadWriteLock(true);
        
        for (int i = 0; i < 6; i++) {
            new Lector(i, cv, L).start();
        }
        
        for (int i = 0; i < 3; i++) {
            new Thread(new Escritor(i, cv, L)).start();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
