/*
 * 
 * 
 */
package isdd.practice3.view;

import javax.swing.*;

/**
 *
 * @author Pepe
 */
public class DBView extends JFrame {

    /**
     * Creates new form DBView
     */
    public DBView() {
        setResizable(false);
        setLocationRelativeTo(null);
        
        initComponents();
        initJMenu();
    }
    
    private void initJMenu() {
        menuBar = new JMenuBar();
        mMain = new JMenu("Database");
        mExit = new JMenuItem("Exit");
        mExit.setActionCommand("Exit");
        
        mMembers = new JMenu("Members");
        mMemManage = new JMenuItem("Members Management");
        
        mTrainers = new JMenu("Trainers");
        mTrainManage = new JMenuItem("Trainers Management");
        
        mActivities = new JMenu("Activities");
        
        menuBar.add(mMain);
        mMain.add(mExit);
        
        menuBar.add(mMembers);
        mMembers.add(mMemManage);
        
        menuBar.add(mTrainers);
        mTrainers.add(mTrainManage);
        
        menuBar.add(mActivities);
        
        setJMenuBar(menuBar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

public JMenuBar menuBar;
public JMenu mMain;
public JMenuItem mExit;

public JMenu mMembers;
public JMenuItem mMemManage;

public JMenu mTrainers;
public JMenuItem mTrainManage;

public JMenu mActivities;
}
