
/**
 * Author:  Pepe
 * Created: 9 ene 2023
 */

-- Find activity members -> Oracle:

CREATE OR REPLACE PROCEDURE ISDD_003.FINDACTIVITYMEMBERS(ACTID IN ACTIVITY.A_ID%TYPE, C_MEMBERS IN OUT SYS_REFCURSOR) IS
BEGIN 
	OPEN C_MEMBERS FOR SELECT m.M_NUM, m.M_NAME, m.M_EMAILMEMBER FROM 
            (PERFORMS p INNER JOIN "MEMBER" m ON p.P_NUM = m.M_NUM) WHERE p.P_ID = ACTID;
END;


-- Mariadb:
DELIMITER //

CREATE PROCEDURE FINDACTIVITYMEMBERS(
  IN ACTID CHAR(4)
)
 BEGIN
  select m.M_NUM, m.M_NAME, m.M_EMAILMEMBER from PERFORMS p inner join `MEMBER` m on p.P_NUM = m.M_NUM WHERE p.P_ID = ACTID;
 END;
//

DELIMITER ;



