/*
 * 
 * 
 */
package pcd.practica4;

/**
 *
 * @author Pepe
 */
public class ColaFrame extends java.awt.Frame {

    /**
     * Creates new form ColaFrame
     */
    public ColaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        final int ANCHO = 800, ALTO = 450, CAPACIDAD = 10;
        ColaFrame frame = new ColaFrame();
        CanvasCola canvas = new CanvasCola(CAPACIDAD);
        ColaLenta cola = new ColaLenta(10, canvas);
        
        Productor hProd[] = new Productor[4];
        for (int i = 0; i < 4; i++)
            hProd[i] = new Productor(cola);
        Thread hConsu = new Thread(new Consumidor(cola));
        
        canvas.setSize(ANCHO, ALTO);
        frame.setTitle("Representación de la cola lenta");
        frame.setSize(ANCHO, ALTO);
        frame.setLocationRelativeTo(null);
        frame.add(canvas);
        frame.setVisible(true);
        
        for (int i = 0; i < 4; i++)
            hProd[i].start();
        hConsu.start();
        
        try {
            for (int i = 0; i < 4; i++)
                hProd[i].join();
            hConsu.join();
            Thread.sleep(3000);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        System.out.println("practica3.ColaFrame.main() END");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
